### ISSUE TITLE
Evaluate using xdg-basedir crate

### ISSUE THREAD

**Issue by dbrgn** [dbrgn/tealdeer#10]
The [xdg-basedir](https://kiran-kp.github.io/xdg-basedir/xdg_basedir/index.html) crate could make the $XDG_CACHE lookup (usually `~/.cache`) more standards compliant.

A `get_dir` function could be conditionally-compiled for unix and non-unix platforms. On unix, the $XDG_CACHE lookup would be used, on Windows a directory in the user profile that doesn't contain a dot would be used.

**Comment by SShrike** [comment]
Are there any tldr pages for Windows? I thought it was only for OS X/Linux/*nix?

If that's the case, then Windows support isn't required as I doubt their are many users wanted to browse simplified man pages on their Windows machine, and if they really did want to there is always the online repository.

**Comment by SShrike** [comment]
Also, I'd be happy to work on this.

**Comment by dbrgn** [comment]
I'm actually not sure. The current pages don't include Windows support, so I guess we don't need it now. But in theory nothing speaks against supporting powershell commands in the tldr pages...

**Comment by SShrike** [comment]
It shouldn't be too hard to add Windows support in the future anyhow.

**Comment by SShrike** [comment]
I'm finding a lot of newlines and double newlines in your code.

E.g.
```
#[derive(Debug)]
pub enum TldrError {
    CacheError(String),
    UpdateError(String),
}


impl From<ErrCode> for TldrError {
    fn from(err: ErrCode) -> TldrError {
        TldrError::UpdateError(err.to_string())
    }
}
```

*and*

```
impl Cache {

    pub fn new<S>(url: S, os: OsType) -> Cache where S: Into<String> {
        Cache {
            url: url.into(),
            os: os,
        }
    }
```

It's quite unusual and I'm not sure if it is part of your coding style or if they are just mistakes.

**Comment by dbrgn** [comment]
That's probably because of my Python background, where you separate top level functions with two empty lines (as specified by PEP8) :) Does Rust have any conventions on this?

> Also, I recommend this library instead. If only because I prefer the API.

Sure, I don't have experience with either of them :)

**Comment by SShrike** [comment]
> The double empty lines are probably because of my Python background, where you separate top level functions with two empty lines (as specified by PEP8) :) Does Rust have any conventions on this?

I figured it was from Python. Regarding Rust, there really isn't much of formal written convention (at least, I don't think there is), however using double newlines is something you'll never really see in Rust code (and is indeed something I've only seen be used by Python programmers).

> Regarding the second example, I prefer to keep vertical whitespace symmetric, so I'd put an empty line between the impl and the pub fn new lines if there's an empty line following the new method. If new is the only method in the impl block, I'd skip these empty lines.

That's quite an unusual thing to do (at least in my experience), but I'll try my best to keep it in mind.

**Comment by dbrgn** [comment]
Feel free to get rid of the double empty lines.

Regarding the rest, I can try to come up with a sensible rustfmt config.
