### ISSUE TITLE
Switch command-line parsing to clap

### ISSUE THREAD

**Issue by dbrgn** [dbrgn/tealdeer#106]
It's faster and we might be able to auto-generate the autocompletion files (see comment in #86).

(Generating autocompletion doesn't need to be part of this issue.)

Potentially related to #79.

**Comment by dbrgn** [comment]
On that occasion, maybe `-m/--markdown` should be renamed to `-r/--raw`?

**Comment by dbrgn** [comment]
Furthermore, we don't quite follow the spec:

https://github.com/tldr-pages/tldr/blob/master/CLIENT-SPECIFICATION.md#arguments

For example, `-p` is `--pager`, not `--platform`.

**Comment by pksunkara** [comment]
I am a clap maintainer. I can answer any issues for this. We will be releasing a 3.0 beta version soon. You can use the new `clap_derive`.

I was looking at the issues because I didn't like the way the colors are shown. Most of the other clients follow a certain pattern and I got used to that.

**Comment by dbrgn** [comment]
Oh wow. Out of curiosity, today I did a release mode profile with valgrind/callgrind. Here's the call graph of `main`:

![2020-03-07-020409_1920x1065_scrot](https://user-images.githubusercontent.com/105168/76133466-8e3c0080-6018-11ea-8c1b-6a9d7043ec87.png)

On here, the purple part in the bottom is config file TOML parsing. The colorful stuff on the lower right and right side is the actual file loading, tokenization and rendering. And the huge blue chunk is just docopt argument parsing :flushed: 

Of course in absolute numbers it's still quite fast and callgrind does not measure in absolute time but in instructions (so I/O is not considered), but it's still quite a big part of the binary.

We should definitely try clap instead, and then do a comparison :slightly_smiling_face: Maybe I can do a quick draft tomorrow.

**Comment by pksunkara** [comment]
If you want to use clap v3, please use clap_derive from master branch. If not, you should try structopt derive.

**Comment by dbrgn** [comment]
@pksunkara with clap_derive, is there a way to manually print the help from the parsed struct?

(Some flags are only valid in combination with a command.)

**Comment by pksunkara** [comment]
> Some flags are only valid in combination with a command.

You should be able to define all that in clap itself which does parsing and errors with help messages when condition fails.

**Comment by dbrgn** [comment]
@pksunkara let's continue the discussion in https://github.com/dbrgn/tealdeer/pull/108!

**Comment by dbrgn** [comment]
In case we fully implement the client spec, this will fix #120.
