### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by optikfluffel** [dbrgn/tealdeer#117]
`tldr.sh` seems to have some kind of syntax highlighting for the example commands:

![Screenshot from tldr.sh](https://tldr.sh/assets/img/screenshot.png)

Would be nice to have this in tealdeer as well.

**Comment by dbrgn** [comment]
That should already be possible by using styles, check out the README. Check out this (not particularly beautiful) example:

![2020-05-06-154646_1183x1064_scrot](https://user-images.githubusercontent.com/105168/81184576-d5ab2280-8fb0-11ea-8104-a0d127170050.png)
