### ISSUE TITLE
Yo, thank you

### ISSUE THREAD

**Issue by felix91gr** [dbrgn/tealdeer#121]
That's it. Thank you so much. `tldr` saves me time, but more importantly, it saves me on frustration and anxiety of reading manpages. 

Having it available in Rust is all the better: it flows seamlessly with my shell because it's so fast.

Also I love the teal deer in the README. I always forget about its existence, and rediscovering it is such a pleasure :blue_heart: 

Thank you!

**Comment by dbrgn** [comment]
Thanks! :heart:
