### ISSUE TITLE
Broken `zsh` completion

### ISSUE THREAD

**Issue by BachoSeven** [dbrgn/tealdeer#137]
Hi! After installing latest tag release, attempting to complete in `zsh` gives the following error:
``` sh
_arguments:comparguments:325: invalid argument: (-h --help -v --version --color){--color}[Controls when to use color]:when:((\n\t    always\n\t    auto\n\t    never\n        ))
_arguments:comparguments:325: invalid argument: (-h --help -v --version --color){--color}[Controls when to use color]:when:((\n\t    always\n\t    auto\n\t    never\n        ))
_arguments:comparguments:325: invalid argument: (-h --help -v --version --color){--color}[Controls when to use color]:when:((\n\t    always\n\t    auto\n\t    never\n        ))
```

**Comment by dbrgn** [comment]
Hm, unfortunately I'm not familiar with the zsh completion format... Are you familiar with it? Do you see what the problem is?

**Comment by BachoSeven** [comment]
I have written only basic completions but I will try.

The breakage is definitely due to this [commit](https://github.com/dbrgn/tealdeer/commit/f757389df99b358623013be6d31dcc3b91bee0a4#diff-d45a132e5beacc572785c83c37ec5190), and I think based on the rest of the syntax it should be like this, as the new `--color` argument which seems to be the problem doesn not need the extra arguments as it is one of the "only-long" options, like `--seed-config`:
``` diff
--- zsh_tealdeer.orig	2020-09-04 01:22:52.766594547 +0200
+++ /usr/share/zsh/site-functions/_tldr	2020-09-04 01:23:03.139927740 +0200
@@ -25,11 +25,11 @@
 	"($I -q --quiet)"{-q,--quiet}"[Suppress informational messages]"
 	"($I)--config-path[Show config file path]"
 	"($I)--seed-config[Create a basic config]"
-	"($I --color)"{--color}'[Controls when to use color]:when:((
+	"($I)--color[Controls when to use color]:when:((
 	    always
 	    auto
 	    never
-        ))'
+        ))"
 	'(- *)'{-h,--help}'[Display help]'
     	'(- *)'{-v,--version}'[Show version information]'
     	'*:file:_files'
```

**Comment by BachoSeven** [comment]
I opened a PR with the aforementioned solution, if you want to test it in `zsh` you just need to install it and run `autoload -Uz compinit && compinit`, and you should be able to see if it works.

**Comment by dbrgn** [comment]
Thanks for the instructions, seems to work!
