### ISSUE TITLE
Double Curly Brackets in Example Code (no token replacement)

### ISSUE THREAD

**Issue by cmaahs** [dbrgn/tealdeer#143]
While this issue is likely something that needs to be defined at the syntax specification level over at tldr-pages, it is worth mention here for some thoughts that can perhaps be brought to them to help drive a definition in the specification.

There is at least one issue at [tldr-pages](https://github.com/tldr-pages/tldr/issues/4148) that references this.  

Using go templates is becoming a fairly common way to bring "custom" formatting to output.  And unfortunately a big component of that is surrounding the template in double curly brackets, {{ .Variable.Path }}.  

A custom md file I use to append to the docker.md is this:

```plaintext
# docker

- Quickly target those GB sized images

`docker images --format "{{.Size}}\t{{.Repository}}:{{.Tag}}" | grep 'GB\t'`
```

No worries if the issue is simply closed, just wanted to bring some attention to it.

**Comment by dbrgn** [comment]
Thanks for bringing this up!

I'm happy to implement a solution (or accept a PR) once it is decided on the tldr-pages project level how we should deal with this! It doesn't really make sense to implement client-specific solutions if they don't work across all clients.

I'l close this for now, but feel free to comment if something changes, we can always re-open :slightly_smiling_face:
