### ISSUE TITLE
A challenger emerges ...

### ISSUE THREAD

**Issue by gutjuri** [dbrgn/tealdeer#145]
Hello there,
I modified an existing tldr client to be extremly fast. I did some benchmarks and it seems to be faster than tealdeer, though not by a lot. You can find it here: https://github.com/gutjuri/fast-tldr
I'd appreciate it if you could add it to your listed benchmarks :) If problems occur during the installation, let me know.
Best regards, Juri

**Comment by dbrgn** [comment]
Hi @gutjuri. Nice! See #129, feel free to add a comment there with a link to your client!
