### ISSUE TITLE
Allow italics styling

### ISSUE THREAD

**Issue by xeruf** [dbrgn/tealdeer#146]
I like how https://github.com/raylee/tldr-sh-client shows example arguments in italics, and would like to configure tealdeer similarly, but apparently that's not supported yet :/

**Comment by niklasmohrin** [comment]
Note for PR author: There are other clients that implement this as well, if you are not fluent in `sh` and `sed` 🤣 , for example

https://github.com/elecprog/tldr/blob/master/pages/prettyprint.go

**Comment by dbrgn** [comment]
The crate we're using (https://docs.rs/ansi_term/) already supports italics, so adding support should be pretty simple 🙂

**Comment by dmaahs2017** [comment]
It looks like to implement this one would have to:

- Add italic option to the RawStyle struct.
- maybe update the tokenizer to specify exactly where the italics go within a line, not clear to me yet
- update the formatter to print italics with ansi_term
