### ISSUE TITLE
Question::What is the default path used by tldr for cache management ...

### ISSUE THREAD

**Issue by shamb0** [dbrgn/tealdeer#151]
Under Linux/Ubuntu system, What is the default path used by tldr for cache management.

For eg, options '--update' & '--clear-cache' updates and clear the tldr cache ...

Is there any config option to move cache to custom location ?

**Comment by dbrgn** [comment]
Under Linux, the XDG cache directory (by default ~/.cache/tealdeer) is used. It can be overridden using the `TEALDEER_CACHE_DIR` variable.

This should probably be documented in the docs, and there should be a command to list all directories...

**Comment by shamb0** [comment]
Nice, cfg option "TEALDEER_CACHE_DIR" is working fine.

Thanks

**Comment by dbrgn** [comment]
I'll re-open the issue to keep it as a reminder to update the docs :slightly_smiling_face:
