### ISSUE TITLE
Unknown flag: '-t' error on Arch

### ISSUE THREAD

**Issue by IevgenSobko** [dbrgn/tealdeer#154]
Installed tealder with `cargo install tealder`, but no matter what options I use it provides me the same output 

```
Unknown flag: '-t'
```
Verified also on latest Manjaro with the same result and AUR version.

![2020-11-12_21-42](https://user-images.githubusercontent.com/14232100/98988514-7108eb80-2530-11eb-8ea5-fed522882862.png)

**Comment by dbrgn** [comment]
I cannot reproduce this issue. I suspect it has something to do with your shell completions.

What shell do you use, and if you installed the package through cargo, did you manually install any completions for it? Maybe completions for a different tldr client are installed?

**Comment by IevgenSobko** [comment]
@dbrgn Thaks for the help it was really my alias in bash to use specific color theme for NodeJS tldr client that I've used before.
