### ISSUE TITLE
Release Using the GitHub Action

### ISSUE THREAD

**Issue by black7375** [dbrgn/tealdeer#165]
These advantages include:
- Secret Token
- MacOS Supported
- It is automatically created at release.

**Comment by black7375** [comment]
It work in process
https://github.com/black7375/tealdeer/blob/master/.github/workflows/release.yml

I'll make PR.

Now, Have upload file issue.
https://github.com/softprops/action-gh-release/issues/82

**Comment by dbrgn** [comment]
Fixed in #240.
