### ISSUE TITLE
zsh completion issue due to new '[.md' page

### ISSUE THREAD

**Issue by cho-m** [dbrgn/tealdeer#166]
Currently, ZSH tab-completion is erroring with:
```console
❯ tldr <tab>
_values:compvalues:11: invalid value definition: [
```

This may be due to TLDR adding a new page for ['\[.md' recently](https://github.com/tldr-pages/tldr/blob/master/pages/common/%5B.md)

Taking a look at [ZSH Parameter Expansion](http://zsh.sourceforge.net/Doc/Release/Expansion.html#Parameter-Expansion-Flags), one option seems to be to use the `q` option:

> q
>
> Quote characters that are special to the shell in the resulting words with backslashes; unprintable or invalid characters are quoted using the $’\NNN’ form, with separate quotes for each octet.
> 
> If this flag is given twice, the resulting words are quoted in single quotes and if it is given three times, the words are quoted in double quotes; in these forms no special handling of unprintable or invalid characters is attempted. If the flag is given four times, the words are quoted in single quotes preceded by a $. Note that in all three of these forms quoting is done unconditionally, even if this does not change the way the resulting string would be interpreted by the shell.
> 
> If a q- is given (only a single q may appear), a minimal form of single quoting is used that only quotes the string if needed to protect special characters. Typically this form gives the most readable output.
> 
> If a q+ is given, an extended form of minimal quoting is used that causes unprintable characters to be rendered using $’...’. This quoting is similar to that used by the output of values by the typeset family of commands.
> 
>

**Comment by dbrgn** [comment]
Thanks! Since I'm not a zsh user myself: Tested pull requests are welcome!

**Comment by cho-m** [comment]
I'll test it a bit and try some other options.

I do see an issue when dealing with an empty cache since it tab-completes an escaped empty string.
```zsh
❯ tldr <tab>

❯ tldr \'\'
```

**Comment by cho-m** [comment]
Created PR using different array solution rather than `q` option to resolve a few other issues.

**Comment by lovetoburnswhen** [comment]
Has this been released yet?

**Comment by dbrgn** [comment]
@lovetoburnswhen no, not yet.
