### ISSUE TITLE
Create tests for Custom Pages and Patches Functionality

### ISSUE THREAD

**Issue by dmaahs2017** [dbrgn/tealdeer#180]
Create Integration and Unit Tests for functiality added in PR #142.

Address issue: #180

**Comment by dbrgn** [comment]
@dmaahs2017 from your comment in #142 it seems you're willing to implement these tests, right? I assigned the issue to you, otherwise just let me know 🙂

**Comment by dmaahs2017** [comment]
> @dmaahs2017 from your comment in #142 it seems you're willing to implement these tests, right? I assigned the issue to you, otherwise just let me know 🙂 

Yep, thanks!

**Comment by dmaahs2017** [comment]
Closing this because PR #183 was merged

**Comment by dmaahs2017** [comment]
@niklasmohrin @dbrgn can we close this issue? or is there a way to mark it as complete as opposed to just closing it?

**Comment by dbrgn** [comment]
No, closing is fine!

**Comment by niklasmohrin** [comment]
@dmaahs2017 A note on that: When your initial PR comment has something like "fixes #xxx", the issue will be closed automatically when the PR is merged

https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

**Comment by dmaahs2017** [comment]
> A note on that: When your initial PR comment has something like "fixes #xxx", the issue will be closed automatically when the PR is merged

Oh that's cool, Today I learned 🙂
