### ISSUE TITLE
not found in cache

### ISSUE THREAD

**Issue by horseinthesky** [dbrgn/tealdeer#194]
Ubuntu 20.04 WSL.

Installed via `cargo`
```
which tldr
/home/horseinthesky/.cargo/bin/tldr
```

Continuously shows:
```
tldr python+binary+search
Page python+binary+search not found in cache
Try updating with `tldr --update`, or submit a pull request to:
https://github.com/tldr-pages/tldr
```
even after
```
tldr --update
Successfully updated cache.
```

No successful runs.

**Comment by niklasmohrin** [comment]
What is the expected result here? Does this happen with _all_ queries, e.g. with `tldr tar`?

Unless that is the case, I am afraid that you misunderstood what kind of content is served through tealdeer. The pages come from https://github.com/tldr-pages/tldr, a collection of help pages about command line programs, but not programming guides. For that, I can recommend cheat.sh though

**Comment by horseinthesky** [comment]
@niklasmohrin Thank you. cheat.sh is a great addition to this tool
