### ISSUE TITLE
Download docs archive from mirror sites?

### ISSUE THREAD

**Issue by hyrious** [dbrgn/tealdeer#199]
https://github.com/dbrgn/tealdeer/blob/123c8096309302fa2728186180ca24a8bf9ab821/src/main.rs#L56

Instead of using proxy, it is also a good choice to use mirror sites links.
For example https://download.fastgit.org/tldr-pages/tldr/archive/master.tar.gz

Simillar function can be found in [ruby gem bundler](https://bundler.io/man/bundle-config.1.html#MIRRORS-OF-GEM-SOURCES).

**Comment by niklasmohrin** [comment]
Good idea, this should be an easy but worthwhile addition to the existing configuration options!

**Comment by dbrgn** [comment]
We don't download from GitHub anymore, so this is obsolete.
