### ISSUE TITLE
Docs: custom patches note

### ISSUE THREAD

**Issue by dmaahs2017** [dbrgn/tealdeer#245]
@dbrgn and @niklasmohrin I don't think this note applies anymore since we are inserting a newline between the files at the IO level

![Screenshot_20220101-133814_DuckDuckGo.jpg](https://user-images.githubusercontent.com/18738072/147858778-73652e9f-72b1-4c8f-9e9b-85c2414eae8e.jpg)

**Comment by dbrgn** [comment]
Ugh, I thought I removed that note? Apparently I forgot 🙂
