### ISSUE TITLE
Newline added before custom patches may cause issues on windows

### ISSUE THREAD

**Issue by dmaahs2017** [dbrgn/tealdeer#246]
I'm not sure if this is a real issue or not. But I just realized that when we put a "\n" between a page and a patch file at the IO level we may be causing compatibility issues on windows. Since windows newlines are "\r\n". Haven't tested this yet, but wanted to make a note of it before I forget.

**Comment by niklasmohrin** [comment]
Shouldnt be a problem, `BufRead::read_line` only cares about LF and we `trim_end` before looking at it more closely. In theory, this should eliminate any crlf shenanigans. Good thinking, still 👍

**Comment by dbrgn** [comment]
Yep, this shouldn't be an issue. I'll test it tomorrow to make sure.

**Comment by dbrgn** [comment]
Everything works perfectly fine 🙂

**Comment by dmaahs2017** [comment]
Thanks for checking it out @dbrgn and @niklasmohrin! 😄
