### ISSUE TITLE
Use anyhow

### ISSUE THREAD

**Issue by dbrgn** [dbrgn/tealdeer#248]
Using anyhow instead of custom error types and strings is probably a good idea.

I started the work to port the codebase to anyhow.

**Comment by niklasmohrin** [comment]
Lets benchmark afterwards, I am curious

**Comment by dbrgn** [comment]
What would you benchmark, the error branches? I don't think it should affect the success branches at all (and the error branches don't matter).

**Comment by niklasmohrin** [comment]
> I don't think it should affect the success branches at all

I would expect that too, but I want to be sure 😅

**Comment by dbrgn** [comment]
Fixed in #249.
