### ISSUE TITLE
`whereis` doesn't support flags or arguments anymore.

### ISSUE THREAD

**Issue by alanldawkins** [dbrgn/tealdeer#269]
Platform: macOS 10.15.7

From `man whereis`:
```
COMPATIBILITY
     The historic flags and arguments for the whereis utility are no longer available in this version.
```

**Comment by niklasmohrin** [comment]
Is this about the content of a page? In this case, please direct your issue towards tldr-pages/tldr. Otherwise, please describe your problem in more detail :)

**Comment by dbrgn** [comment]
I'll close this for now, but you can still leave a comment if this is about teldeer!
