### ISSUE TITLE
Automatically update cache if needed

### ISSUE THREAD

**Issue by PAI5REECHO** [dbrgn/tealdeer#275]
```console
$ tldr blah
Warning: Cache not found. Please run `tldr --update`.
```

Would be nice if there was a way to just have this done for me automatically without telling me to run the command manually.

**Comment by dbrgn** [comment]
Do [automatic cache updates](https://dbrgn.github.io/tealdeer/config_updates.html) help?

**Comment by niklasmohrin** [comment]
Related: #250

**Comment by dbrgn** [comment]
Ah good point, I already forgot about #251 which should resolve this issue.

I'll prepare a new release soon, it's been a while.
