### ISSUE TITLE
Using tealdeer in Rust as a library

### ISSUE THREAD

**Issue by rbozan** [dbrgn/tealdeer#283]
I was wondering if we can `tealdeer` in Rust without using the CLI but as an usual library. It doesn't seem like it as there is no `lib.rs`. Is there any plans to have it?

**Comment by dbrgn** [comment]
No, there are no such plans at the moment. For that we would need to abstract away the configuration and cache management, right now the assumption is always that it's a CLI user application.

**Comment by niklasmohrin** [comment]
Additionally, I think the ability to break interfaces and change signatures in the code currently outweighs all arguments for tealdeer-as-a-library.

**Comment by dbrgn** [comment]
I'll close this for now. It's unlikely to be implemented.
