### ISSUE TITLE
Release for v1.6.1 tag not present

### ISSUE THREAD

**Issue by adrienthebo** [dbrgn/tealdeer#301]
Hello!

I use a simple [asdf plugin](https://github.com/adrienthebo/asdf-tealdeer/blob/main/bin/list-all#L10) to install tealdeer; it assumes that all tealdeer tags have a corresponding [github release](https://github.com/adrienthebo/asdf-tealdeer/blob/main/bin/install#L54) but at present v1.6.1 doesn't appear to have a release. Would it be possible to get the v1.6.1 release uploaded?

Thanks for all of your work!

**Comment by niklasmohrin** [comment]
Yes, of course!

**Comment by dbrgn** [comment]
Ah, thanks for the reminder! Version 1.6.1 was still in the draft state 🙂  I published it.
