### ISSUE TITLE
Feat: add --markdown CLI flag

### ISSUE THREAD

**Issue by benelan** [dbrgn/tealdeer#302]
I use a tool called [`navi`](https://github.com/denisidoro/navi), which supports searching tldr cheatsheets 

```sh
navi --tldr <command>
```

However, navi requires the tldr client to support the `--markdown` flag [like the node client has](https://github.com/tldr-pages/tldr-node-client/blob/77de3a403bce704242aab8ffe57774696f53843a/README.md?plain=1#L34). When I tried using tealdeer with navi I got the following error:

```sh
Failed to call: 
tldr grep --markdown
 
Output:


Error:
error: Found argument '--markdown' which wasn't expected, or isn't valid in this context

	If you tried to supply `--markdown` as a value rather than a flag, use `-- --markdown`

USAGE:
    tldr <COMMAND|--render <FILE>>

For more information try --help


Note:
Please make sure you're using a version that supports the --markdown flag.
If you are already using a supported version you can ignore this message. 
The tldr client written in C (the default one in Homebrew) doesn't support markdown files, so navi can't use it.
The client written in Rust is recommended. The one available in npm works, too.
```

Woud you consider adding the `--markdown` flag? Thanks!

Edit:
I can take a stab at a PR if it's something you'd consider approving.

**Comment by dbrgn** [comment]
That flag in tealdeer is currently called `-r / --raw`. As long as the [client specification](https://github.com/tldr-pages/tldr/blob/main/CLIENT-SPECIFICATION.md) doesn't standardize this flag, I'd be reluctant to change it in tealdeer, just to accomodate a third party tool.

Adding an invisible alias would be a possibility, but I think trying to standardize this flag would be the better way forward in the long term. (The place to suggest such a standardization would be over at https://github.com/tldr-pages/tldr.)

**Comment by benelan** [comment]
Gotcha, thanks for the insight!
