### ISSUE TITLE
Error: Could not update cache

### ISSUE THREAD

**Issue by ShengYenPeng** [dbrgn/tealdeer#304]
Hi :)

When I execute : `tldr -u`,

I got following message:
```
Error: Could not update cache

Caused by:
    0: error sending request for url (https://tldr.sh/assets/tldr.zip): error trying to connect: dns error: failed to lookup address information: Name or service not known
    1: error trying to connect: dns error: failed to lookup address information: Name or service not known
    2: dns error: failed to lookup address information: Name or service not known
    3: failed to lookup address information: Name or service not known
```

Should I do some setting or try something to narrow down the issue?

------ Version Information -----

```
tealdeer version: 1.6.1

OS: CentOS Linux release 7.3.1611
```

**Comment by ShengYenPeng** [comment]
I can get https://tldr.sh/assets/tldr.zip and copy it to working environment,
can I update tldr with this zip?

**Comment by dbrgn** [comment]
Use the command `tldr --show-paths` to list the paths used. On my system, the "Cache dir" is here: `/home/danilo/.cache/tealdeer`

This means that you can unpack the ZIP file so that the directory looks like this:

```
/home/danilo/.cache/tealdeer/
└── tldr-pages
    ├── index.json
    ├── LICENSE.md
    ├── pages
    ├── pages.ar
    ├── pages.bn
    ...
```
