### ISSUE TITLE
Include shell completion in crates.io releases?

### ISSUE THREAD

**Issue by bnoctis** [dbrgn/tealdeer#332]
Hi, I packaged and maintain tealdeer [in Debian](https://tracker.debian.org/pkg/rust-tealdeer). Our current packaging approach, in the Debian Rust Team, uses crates.io release tarballs. It unfortunately doesn't include the completions, thus I have to use [a patch to add them back](https://salsa.debian.org/rust-team/debcargo-conf/-/blob/master/src/tealdeer/debian/patches/provide-completion.patch).

Is it feasible to include them? Otherwise a manual copy may become out of sync.

**Comment by niklasmohrin** [comment]
Sounds reasonable to me, can do :)
