### ISSUE TITLE
Help getting custom pages to work

### ISSUE THREAD

**Issue by nkh** [dbrgn/tealdeer#338]
I'm trying to add a custom page without success. This is most probably me not understanding what to do.

I get the custom pages location with the --show-paths option, create the directory

I tried to add a page, say nadim.md, in the above directory, in it's sub directory .../pages, in it's sub directory ...pages/common.

I ran tldr -u every time 

the nadim page is not available in any of those cases.

I did the same for an existing page, perl.md, same non-results

Is  this still supported? what would be the exact procedure to succeed with it ?

**Comment by niklasmohrin** [comment]
Hey, it looks like your file ending is wrong, we look for files ending in ".page" and ".patch" (see https://dbrgn.github.io/tealdeer/usage_custom_pages.html). We are thinking about allowing something like ".page.md" in the future though (#320)

**Comment by nkh** [comment]
Thank you,

 it's so ... illogical
 
 but I missed it, the decision is illogical but the blindness is mine

**Comment by zedseven** [comment]
@nkh, if you need/prefer a `.md` extension, I still have my branch for the referenced PR open—you can build it from source, and it will use `.page.md` and `.patch.md` instead of the current extensions.

https://github.com/zedseven/tealdeer/tree/custom-pages-md

**Comment by nkh** [comment]
@zedseven 

Thanks a lot but I ended up writing my own client after playing a bit with the tldr concept.

I still appreciate the help I got in this project and the software itself.
