### ISSUE TITLE
tldr -u take long time to succeed

### ISSUE THREAD

**Issue by nkh** [dbrgn/tealdeer#339]
I have a slow internet which may be part of the problem

cloning the full tldr pages repo takes 1 minute

shallow cloning the tldr pages repo takes 20 seconds

a git pull take 0.5 seconds

tldr -u takes 35 seconds, and 25 seconds with a warm cache, are those normal times?

**Comment by niklasmohrin** [comment]
Yes, these times seem normal as we basically do a new shallow clone on each update (we download all pages in an archive). One thing that might improve your experience soon is the planned feature of downloading pages only in the needed languages, avoiding extra translations (#335).
