### ISSUE TITLE
Add a random flag like node client

### ISSUE THREAD

**Issue by MustCodeAl** [dbrgn/tealdeer#340]
it would be nice to see a random tldr every time terminal is opened to help with command line learning and configurable number of commands to show for that tldr page.

`tldr --random` 

```
  page: tar

  Archiving utility.
  Often combined with a compression method, such as gzip or bzip2.
  More information: https://www.gnu.org/software/tar.


  - [c]reate an archive and write it to a [f]ile:
    tar cf path/to/target.tar path/to/file1 path/to/file2 ...

  - [c]reate a g[z]ipped archive and write it to a [f]ile:
    tar czf path/to/target.tar.gz path/to/file1 path/to/file2 ...
```

**Comment by MustCodeAl** [comment]
now i have added [changes](https://github.com/dbrgn/tealdeer/compare/main...MustCodeAl:tealdeer:main)

**Comment by niklasmohrin** [comment]
I am not sure if I like this being its own flag of tealdeer, when the same behavior can already be achieved in one shell command, for example in bash: `tldr -q $(tldr -q --list | shuf -n1)`. We could however write this down as an example somewhere in the documentation as a nice idea. What do you think?

**Comment by MustCodeAl** [comment]
i had no idea of that command existing 😅, that would be cool

**Comment by dbrgn** [comment]
I agree, I don't think a "random" command belongs in tealdeer, since this can be achieved with external tools.

I think the use case is a bit obscure, but it wouldn't hurt to add a "Tips & Tricks" section to the docs.
