### ISSUE TITLE
How to migrate from TEALDEER_CACHE_DIR to config file

### ISSUE THREAD

**Issue by elyashivhazan** [dbrgn/tealdeer#344]
Hi, I set this `TEALDEER_CACHE_DIR="${XDG_DATA_HOME}/tealdeer"` and now I don't know how to migrate it to the config file, I assume you must set absolute path but if that the case I think it's limiting a lot.

**Comment by niklasmohrin** [comment]
It's currently not implemented, see #156 (closing as duplicate)
