### ISSUE TITLE
Support for clap version 4

### ISSUE THREAD

**Issue by plugwash** [dbrgn/tealdeer#350]
Hi.

I am part of the Debian rust team and we would like to reduce the number of clap versions we are shipping. Is there any chance of an update to support clap version 4?

**Comment by dbrgn** [comment]
Yeah, I think that should be doable. Can't promise a timeline, but a release by the end of the year should be realistic.

**Comment by dbrgn** [comment]
(If someone has enough free time: A PR for the clap update would be welcome 😄)

**Comment by dbrgn** [comment]
Ahh, it seems I already started the work last year(!) and then it got stuck: https://github.com/dbrgn/tealdeer/pull/298 I'll try to finish that.
