### ISSUE TITLE
support pagination

### ISSUE THREAD

**Issue by tamird** [dbrgn/tealdeer#36]
Currently output will happily flow when the terminal is smaller than the output.

**Comment by dbrgn** [comment]
Isn't that what tools like `less` and `more` are for?

**Comment by tamird** [comment]
Yes, and tools like git that do this properly automatically detect when a
pager is needed; they don't make the user do it.

**Comment by dbrgn** [comment]
True.

It's not a priority for me personally, but I'd accept pull requests :)
