### ISSUE TITLE
Documentation out of date with release

### ISSUE THREAD

**Issue by EoinFarrell** [dbrgn/tealdeer#363]
Documentation states that custom pages should use the naming scheme `xxx.page.md`, links:

- https://github.com/dbrgn/tealdeer/blob/main/docs/src/usage_custom_pages.md
- https://dbrgn.github.io/tealdeer/usage_custom_pages.html

The naming scheme was changed from `xx.page` to `xxx.page.md` in #322, merged on the 2024-02-15. But the latest release, [v1.6.1](https://github.com/dbrgn/tealdeer/blob/main/CHANGELOG.md#v161-2022-10-24) is from 2022-10-24. 

This discrepency leads to problems, as if you follow the documentation and use the `xxx.page.md`, your custom pages will not be found.

New release is required to align main and release version.

**Comment by EoinFarrell** [comment]
There could be other problems/descrepencies between the latest release and the latest docs, but this is the only one I have so far come across since starting to use tealdeer. Issues such as #356 could be related to this also, if other users are thinking they are using an out of date version.

**Comment by niklasmohrin** [comment]
Thanks for the report! We are already tracking this problem in #358, so I am going to close this as duplicate
