### ISSUE TITLE
Any plans for M1 Mac?

### ISSUE THREAD

**Issue by sarg3nt** [dbrgn/tealdeer#365]
I'm writing the [asdf-tealdeer](https://github.com/sarg3nt/asdf-tealdeer) plugin to automate install of tealdeer with asdf and mise and noticed there is no M1 Mac binary. Are there any plans to add this as a build target?

**Comment by niklasmohrin** [comment]
Sounds good and should be easy :)

**Comment by dbrgn** [comment]
This became possible (without paying) since January: https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/ I'll give it a stab.

**Comment by dbrgn** [comment]
Ah, wait, we're talking about Rust and it's great cross-compilation features... No special runner is required for that 🙂

**Comment by dbrgn** [comment]
ARM builds should be generated for the next release (soon).
