### ISSUE TITLE
Publish new releases

### ISSUE THREAD

**Issue by yonas** [dbrgn/tealdeer#366]
1. Publish a new release immediately to include bug fixes in dependencies since 2022.

2. Publish second new release.

My suggestions on what should be included in the second release:
  - https://github.com/dbrgn/tealdeer/issues/350
  - https://github.com/dbrgn/tealdeer/issues/349

**Comment by niklasmohrin** [comment]
A new release will be published when some more ongoing work is merged

> Publish a new release immediately to include bug fixes in dependencies since 2022.

Do any of these bugs affect tealdeer functionality?
