### ISSUE TITLE
Speed comparison

### ISSUE THREAD

**Issue by dbrgn** [dbrgn/tealdeer#38]
A command line tool for quickly looking up a command should be fast.

Is this client faster than others? If yes, add it to the README.

**Comment by dbrgn** [comment]
Test case: Measuring real time for `tldr tar` using the `time` command.

I measured the command 5 times and calculatet the average.

**[Tealdeer](https://github.com/dbrgn/tealdeer)**

    cd tealdeer
    cargo build --release
    time target/release/tldr tar

Times: `15ms / 11ms / 5ms / 5ms / 11ms` -> `9.4ms`

**[C Client](https://github.com/tldr-pages/tldr-cpp-client)**

    cd tldr-cpp-client
    make
    ./tldr -u
    time ./tldr tar

Times: `11ms / 5ms / 12ms / 11ms / 15ms` -> `10.8ms`

**[NodeJS Client](https://github.com/tldr-pages/tldr)**

    npm install tldr
    node_modules/.bin/tldr --update
    time node_modules/.bin/tldr tar

Times: `169ms / 171ms / 170ms / 170ms / 170ms` -> `170.0ms`

**[Python client](https://github.com/lord63/tldr.py)**

    cd tldr.py
    python3 -m venv venv
    venv/bin/pip install .
    git clone https://github.com/tldr-pages/tldr source
    venv/bin/tldr init
    venv/bin/tldr reindex
    time venv/bin/tldr find tar

Times: `152ms / 148ms / 151ms / 158ms / 140ms` -> `149.8ms`

**[Bash client](https://github.com/pepa65/tldr-bash-client)**

    cd tldr-bash-client
    ./tldr -u
    time ./tldr tar

Times: `15ms / 19ms / 22ms / 25ms / 24ms` -> `21.0ms`

**[Go client by k3mist](https://github.com/k3mist/tldr/)**

    cd dist/build/linux
    ./tldr tar
    time ./tldr tar

Times: `98ms / 96ms / 100ms / 95ms / 101ms` -> `98.8ms`

**[Haskell client](https://github.com/psibi/tldr-hs)**

I didn't manage to compile this:

```
stack setup
Downloaded lts-10.0 build plan.    
AesonException "Error in $.packages.cassava.constraints.flags['bytestring--lt-0_10_4']: Invalid flag name: \"bytestring--lt-0_10_4\""
```

Not sure whether I'm doing this right :)

**[Ruby client](https://github.com/YellowApple/tldrb)**

I didn't manage to compile this:

```rbenv install
Downloading ruby-2.2.2.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.2.tar.bz2
Installing ruby-2.2.2...

WARNING: ruby-2.2.2 is nearing its end of life.
It only receives critical security updates, no bug fixes.


BUILD FAILED (Arch rolling using ruby-build 20171226)

Inspect or clean up the working tree at /tmp/ruby-build.20180211132117.14606
Results logged to /tmp/ruby-build.20180211132117.14606.log

Last 10 log lines:
linking shared-object pathname.so
make[2]: Leaving directory '/tmp/ruby-build.20180211132117.14606/ruby-2.2.2/ext/pathname'
linking shared-object bigdecimal.so
make[2]: Leaving directory '/tmp/ruby-build.20180211132117.14606/ruby-2.2.2/ext/bigdecimal'
linking shared-object date_core.so
make[2]: Leaving directory '/tmp/ruby-build.20180211132117.14606/ruby-2.2.2/ext/date'
linking shared-object nkf.so
make[2]: Leaving directory '/tmp/ruby-build.20180211132117.14606/ruby-2.2.2/ext/nkf'
make[1]: Leaving directory '/tmp/ruby-build.20180211132117
```

Not sure whether I'm doing this right :)

**[Perl client](https://github.com/skaji/perl-tldr)**

Not sure how to run this without installing it systemwide.

```perl script/tldr 
Can't locate App/tldr.pm in @INC (you may need to install the App::tldr module) (@INC contains: /home/danilo/.opam/tezos/lib/perl5 /usr/lib/perl5/5.26/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.26/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.26/core_perl /usr/share/perl5/core_perl) at script/tldr line 5.
BEGIN failed--compilation aborted at script/tldr line 5.
```

**[Go client by anoopengineer](https://github.com/anoopengineer/tldr/)**

Didn't work for me:

```
cd tldr_0.1.4_linux_amd64
./tldr --update-cache tar
INFO[0000] Downloading fresh tldr's from https://github.com/tldr-pages/tldr/archive/master.zip 
FATA[0000] user: Current not implemented on linux/amd64 
```

**[PHP client](https://github.com/BrainMaestro/tldr-php)**

Didn't work for me:

    cd tldr-php
    composer install
    ./tldr -u

...this blocks forever (>3min).

**Comment by kvnxiao** [comment]
@dbrgn Do you think you can revisit this issue using https://github.com/sharkdp/hyperfine to test the startup time of all the executables? (and also list your hardware, even though it shouldn't matter that much in this use case, it would provide more authenticity to the tests)

**Comment by dbrgn** [comment]
@kvnxiao oh, that's a nice tool! I opened #129.
