### ISSUE TITLE
Static binary builds

### ISSUE THREAD

**Issue by dbrgn** [dbrgn/tealdeer#40]
Create binary releases for people without Rust / Cargo.

**Comment by dbrgn** [comment]
Linux should be easy, but the question is how to create macOS releases without having access to Apple hardware...

**Comment by Dod9er** [comment]
Came here for exact that reason :) Did you already find this one ?
-> https://github.com/japaric/rust-cross#i-want-to-build-binaries-for-linux-mac-and-windows-how-do-i-cross-compile-from-linux-to-mac

**Comment by dbrgn** [comment]
@Dod9er my computer is actually cross compiling different static linux binaries right now (using https://github.com/messense/rust-musl-cross) :) I will upload them as Github release later.

Regarding cross-compilation for macOS, maybe it could be done through TravisCI, which offers macOS targets.

**Comment by Dod9er** [comment]
I think yes, macOS is listed here (never tested as I´m on linux): https://github.com/japaric/trust

**Comment by dbrgn** [comment]
Linux binary releases: https://github.com/dbrgn/tealdeer/releases/tag/v1.0.0

**Comment by dbrgn** [comment]
The script was updated to add a step that strips the binaries, making them considerably smaller (x86_64 is 44% smaller, arm is 47% smaller).

I won't replace the binaries (releases should be immutable), but it would be nice to add an 1.0.1 release with macOS and Windows builds (maybe through Travis / Appveyor).

**Comment by jdvr** [comment]
Current version 1.0.0 is 13 commits above from master, It would be possible to generate a new one?

**Comment by dbrgn** [comment]
@jdvr if you look at the commits, it's all README changes and configfiles :slightly_smiling_face:

**Comment by dbrgn** [comment]
@jdvr no worries :slightly_smiling_face:

**Comment by gd4c** [comment]
Any chance for Windows binaries?

**Comment by dbrgn** [comment]
@gd4c someone would need to set up a CI configuration that outputs x86_64 Windows binaries as build artifact. I only rarely use Windows myself, so it doesn't have high priority for me at the moment.

However, things have gotten easier since we have switched to GitHub actions in the meantime. It probably wouldn't be too hard to create a Windows build artifact for every tagged release.

**Comment by gd4c** [comment]
That would be great! Thanks.

**Comment by dmaahs2017** [comment]
@dbrgn @niklasmohrin [this workflow (see gist)](https://gist.github.com/dmaahs2017/fc96bc9369e62dfdf4034e1c696b837a) is what I use on my personal projects to release OSX, Windows, and Linux static binaries. Maybe this could be useful here

**Comment by niklasmohrin** [comment]
@dmaahs2017 Although I would rather not use any actions from authors other than `actions` and `actions-rs`, I have to admit that these actions seem convenient. Thanks for the hint :smile:

**Comment by dbrgn** [comment]
Fixed by #240. Binaries for macOS and Windows are now provided as well.
