### ISSUE TITLE
Allow specifying multiple operating systems

### ISSUE THREAD

**Issue by jedahan** [dbrgn/tealdeer#45]
So sometimes I'm using tealdeer on my laptop which is macOS, and looking up a utility that is for linux on another box. I have to `-o linux` after seeing that the command is not found.

My workaround is `function tld { tldr $* || tldr -o linux $* }`

I was wondering how you'd feel making this the default behavior.

**Comment by dbrgn** [comment]
Hm, what should happen if a command exists both on Linux and on SunOS (with different TLDR-pages), and you call `tldr` from macOS? :slightly_smiling_face:

**Comment by jedahan** [comment]
Perfect is the enemy of good?

I don't like to make things more complicated, but if you are concerned about confusion with automatic fallback, maybe one of all of:
 * configurable fallback order as cli arguments with a default
 * an indicator of the current fallback at the top or bottom of the rendering
 * maybe making this an upstream thing tldr-pages/tldr with symlinks as fallbacks?

**Comment by BrainMaestro** [comment]
Maybe it could fail, but let the user know that the page exists on another os?

**Comment by dbrgn** [comment]
I'd definitely favor an option where you could specify multiple operating systems in order of precedence (`tldr -o osx,linux`). Now that we have configfile support, the default setting could even be configurable. Alternatively, you could alias `tldr` to `tldr -o osx,linux`.

**Comment by niklasmohrin** [comment]
This issue was closed in #300 :)
