### ISSUE TITLE
--update no longer works behind proxies after switching to reqwest

### ISSUE THREAD

**Issue by aldanor** [dbrgn/tealdeer#65]
It looks like #61 has broken cache updating behind proxies:

Commit e73261542cc601408596fb404c57d54f8cbc6bf7 (just before switching to reqwest):
```sh
$ git checkout e73261542cc601408596fb404c57d54f8cbc6bf7
$ cargo build
$ target/debug/tldr --update
Successfully updated cache.
```

Master branch:

```sh
$ git checkout master
$ cargo build
$ target/debug/tldr --update
Could not update cache: HTTP error: https://github.com/tldr-pages/tldr/archive/master.tar.gz: timed out

```

**Comment by aldanor** [comment]
+@jcgruenhage

**Comment by dbrgn** [comment]
Thanks for testing. Do you know what the reason could be?

Is it a HTTP proxy, or something configured through your network? If it's the former, do you have a `HTTP_PROXY` and/or `HTTPS_PROXY` env variable set up?

**Comment by aldanor** [comment]
Not sure... I do know though that all tools like `git`, `curl`, `wget`, `cargo` etc "just work" without any extra flags or configuring.

I have both `HTTP_PROXY` and `HTTPS_PROXY` pointing to `http://proxy` and I do know that the proxy messes with certificates in some way, so `SSL_CERT_FILE=.../ca-bundle.crt` is also set (not exactly sure which tools use it).

**Comment by dbrgn** [comment]
It looks like we probably have to manually read those two env vars and to set up a [`Proxy`](https://docs.rs/reqwest/0.9.3/reqwest/struct.Proxy.html) object if one of them is set.

**Comment by aldanor** [comment]
This seems to work, just tested:

```rust
extern crate reqwest;

use std::env;
use reqwest::{Client, Proxy, Response, Result};

fn get(url: &str) -> Result<Response> {
    let mut builder = Client::builder();
    if let Ok(ref host) = env::var("HTTP_PROXY") {
        builder = builder.proxy(Proxy::http(host)?);
    }
    if let Ok(ref host) = env::var("HTTPS_PROXY") {
        builder = builder.proxy(Proxy::https(host)?);
    }
    builder.build()?.get(url).send()
}

fn main() {
    let url = "https://github.com/tldr-pages/tldr/archive/master.tar.gz";
    println!("{:?}", get(url).unwrap().status());
}
```

results in an error if you comment out proxy handling, prints 200 otherwise.

**Comment by dbrgn** [comment]
That looks good! @aldanor are you interested in creating a pull request with this fix? The corresponding code [is here](https://github.com/dbrgn/tealdeer/blob/8d2a0d6f9d7ed4c99860e40e2d8b671ae367f305/src/cache.rs#L63).

**Comment by aldanor** [comment]
@dbrgn Sure why not. Will do later today.

**Comment by jcgruenhage** [comment]
Sorry for breaking this, I assumed that reqwest takes care of that tbh :/

**Comment by dbrgn** [comment]
I actually like that reqwest does not take into account some magic side effects like env variables :slightly_smiling_face:

**Comment by jcgruenhage** [comment]
Their readme states that reqwest follows a "batteries included" mindset though, and putting in the proxy manually feels like plugging in the batteries manually. It should be possible to do manual magic, sure, but the default should be to follow the convention of reading HTTP(S)_PROXY

**Comment by aldanor** [comment]
Stuff like parsing HTTP(S)_PROXY vars is just pure boilerplate, so there's a few approaches:

- don't do it automatically and provide no ways of doing it automatically (current reqwest)
- always do it automatically ("batteries included"), e.g. curl etc
- don't do it automatically but provide an easy way to opt-in (e.g. `builder.proxies_from_env()`)

I personally don't see how the third approach could be worse than either of the first two :)

**Comment by aldanor** [comment]
Closing in favor of #68
