### ISSUE TITLE
Use the new index.json file in favor of the deprecated pages/index.json

### ISSUE THREAD

**Issue by mebeim** [dbrgn/tealdeer#80]
Hello, I'm from the [`tldr-pages/tldr`](https://github.com/tldr-pages/tldr) repository, and I'm here to inform you that we recently changed the content of the ZIP archive your client relies upon. Here's a link to the merged PR: [#2862](https://github.com/tldr-pages/tldr/pull/2862).

Inside the generated ZIP archive, a new `/index.json` file has been created, to be used in favor of the now deprecated `/pages/index.json` file, as you can see [here](https://github.com/tldr-pages/tldr-pages.github.io/blob/444ff19d447cdf26d44538666cc1011a3b7c9d29/assets/tldr.zip). Once all the clients are updated, or enough time has passed, **we will completely remove the `/pages/index.json` file from the generated ZIP archive, and only keep the top-level `/index.json`**.

If your client does not rely on the mentioned file to work, you can close this right away, sorry for the trouble! Otherwise, in order to support the upcoming change, this client should be updated to either:

1. Use the `index.json` file served by the static site itself, that is: [`https://tldr.sh/assets/index.json`](https://tldr.sh/assets/index.json).
2. Or use the new top-level `/index.json` file inside the ZIP file served by the static site, which is: [`https://tldr.sh/assets/tldr.zip`](https://tldr.sh/assets/tldr.zip).

Once the above is taken care of, you can close this issue and your client will be marked as up to date in our tracking issue [here](https://github.com/tldr-pages/tldr/issues/2865). This change should be trivial, but if there's any problem, please do let me know.

Thank you for your work and time you put into creating this client and supporting the TLDR pages project!

**Comment by xuchunyang** [comment]
It seems tealdeer is using https://github.com/tldr-pages/tldr/archive/master.tar.gz, there is no any index.json there, maybe this issue can be closed.

**Comment by dbrgn** [comment]
Yep, tealdeer uses the file system to list available pages and does not rely on the index file.

Thanks anyways for the update, @mebeim!

**Comment by mebeim** [comment]
All good then, @dbrgn @xuchunyang thank you guys :)
