### ISSUE TITLE
Color should be turn off automatically if the output is not a terminal device

### ISSUE THREAD

**Issue by xuchunyang** [dbrgn/tealdeer#81]
The color becomes annoying and unwanted when outputs to pipe

    ~ $ tldr ls | less

or Emacs

    (shell-command-to-string "tldr ls")

Some programs such as `ls` provide `--color=auto|never|always`

**Comment by dbrgn** [comment]
:+1: 

Note that if your goal is using a pager to view the pages, you can also [set the use_pager config variable](https://github.com/dbrgn/tealdeer#display).
