### ISSUE TITLE
OS Override / SunOS issue

### ISSUE THREAD

**Issue by malinoskj2** [dbrgn/tealdeer#82]
I am running FreeBSD but trying to use `tldr --os sunos truss` to view the page for SunOS's truss which exists in tldr's cache and am unable to. I am getting: 

```bash
Page truss not found in cache
Try updating with `tldr --update`, or submit a pull request to:
https://github.com/tldr-pages/tldr
```

Looks like this is due to [this line](https://github.com/dbrgn/tealdeer/blob/74c37193e303fb13302c6829b086cf84e2a9b817/src/cache.rs#L136) in `cache.rs`. I can replace the None with Some('sunos') and it lets me see the page as you would expect. I see you have a comment there but not sure how it is relevant.

**Comment by dbrgn** [comment]
Ah, good point :slightly_smiling_face: When I wrote that comment I forgot about the override feature.
