### ISSUE TITLE
Could you tag a new release?

### ISSUE THREAD

**Issue by JacekJagosz** [dbrgn/tealdeer#83]
Sorry for such a stupid question.
I'd want to package it for Solus where releases are strongly advised over git snapshots. And last release lacks a few cool feature git has.
For me just fish autocomplete should be enough to justify a new release.

**Comment by dbrgn** [comment]
Hello. That's not a stupid question, I'll prepare a release soon :)

**Comment by dbrgn** [comment]
Will try to do the release tomorrow, lost some time on #84. If I should forget about it, please feel free to remind me!

**Comment by JacekJagosz** [comment]
@dbrgn Hey, just a friendly reminder

**Comment by dbrgn** [comment]
Finally! 1.2.0 is out. Sorry for the delay!
