### ISSUE TITLE
Compact output

### ISSUE THREAD

**Issue by devnoname120** [dbrgn/tealdeer#88]
This is a bug I've meant to keep track of for a long time. I love tealdeer but the output drives me crazy because it's not compact enough compared to other tldr clients.

Official client:
![image](https://user-images.githubusercontent.com/2824100/66037423-e3c32d00-e50f-11e9-94f6-453bfa79d05c.png)

Tealdeer:
![image](https://user-images.githubusercontent.com/2824100/66037563-30a70380-e510-11e9-86b1-4a8f6ea66a35.png)

As you can see in the screenshot it takes twice the space.

If I remove the excessive newlines, here is what it looks like (better imho):
![image](https://user-images.githubusercontent.com/2824100/66037626-5af8c100-e510-11e9-9f73-0840cf33ed56.png)

I'd suggest to match the official client's output by default. I will give it a shot when I get the chance to, but feel free to fix it.

**Comment by dbrgn** [comment]
IIRC tealdeer simply shows the newlines that are also present in the source file, without trying to collapse them.

I think the additional spacing makes things easier to read, but a "compact" option could be added, so that it's user-configurable.

**Comment by korrat** [comment]
I would like to try this
