### ISSUE TITLE
Allow adding custom entries to pages

### ISSUE THREAD

**Issue by dbrgn** [dbrgn/tealdeer#98]
Sometimes I want to add custom entries to pages that already contain 8 entries. The tldr guidelines only allow up to 8 entries per page.

Maybe we could set up a way to register "patchfiles" with tealdeer (e.g. by placing them somewhere in the `.config/tealdeer/` directory). Those patchfiles would be appended to the corresponding pages when updating the cache.

**Comment by jasonkena** [comment]
Adding custom pages would also be nice

**Comment by dmaahs2017** [comment]
Implementing this in #142
